swagger: '2.0'
schemes:
  - https
basePath: /
info:
  contact:
    email: test@gmail.com
  version: '1.0'
  title: Drafts Test Test Test Test
  x-slack-webhook:
    - cortex-demo
  x-pagerduty-service: PM66VXY 
  x-cortex-tag: Test Webhook
  x-group-id: 00g1gaui8cbR3KKAy4x6
  x-github-repository: nikhilunni/NativeDoc
  x-cortex-link:
    - name: 5xx Runbook
      type: RUNBOOK
      url: https://github.com/nikhilunni
